---
- name: Update MariaDB Dependencies
  shell: >-
    curl -sSL https://downloads.mariadb.com/MariaDB/mariadb_repo_setup
    | bash -s -- --mariadb-server-version="mariadb-11.2"


- name: Install MariaDB (MariaDB repo is slow, this will take some time...)
  dnf:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - MariaDB
      - MariaDB-client
      - MariaDB-server
      - MariaDB-backup
      - tzdata


- name: Install MariaDB DB conf
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
    force: true
    mode: 0644

- name: Install MariaDB Supervisord conf
  template:
    src: supervisor.conf.j2
    dest: /etc/supervisord.d/mariadb.conf
    force: true
    mode: 0644

- name: Disable MariaDB service
  systemd_service:
    name: "mysql"
    enabled: false
    state: stopped
  ignore_errors: true
  when: is_systemd == "True"
