---

- name: Install Redis
  dnf:
    name: redis

- name: Install Redis Conf
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
    force: true
    owner: "redis"
    mode: 0644

- name: Install Redis Supervisord conf
  template:
    src: supervisor.conf.j2
    dest: /etc/supervisord.d/redis.conf
    force: true
    mode: 0644

- name: Create redis run directory
  ansible.builtin.file:
    path: /run/redis
    state: directory
    mode: 0755
    owner: redis
    group: redis

- name: Create tmpfile.d for redis to make sure /run folder created at boot
  template:
    src: tmpfiles.conf.j2
    dest: /usr/lib/tmpfiles.d/redis.conf
    force: true
    mode: 0644

- name: Disable Redis services
  systemd_service:
    name: "{{ item }}"
    enabled: false
    state: stopped
  ignore_errors: true
  with_items:
    - "redis-sentinel"
    - "redis"
  when: is_systemd == "True"
