---
- name: Ensure update script continues to be executable
  file:
    path: "{{ azuracast_setup_update_script }}"
    state: touch
    mode: "a+x"
  loop:
    - "{{ ansible_base }}/update.sh"
    - "{{ www_base }}/backend/bin/console"
  loop_control:
    loop_var: azuracast_setup_update_script

- name: Run AzuraCast Setup (Install Mode)
  become: true
  become_user: azuracast
  shell: >-
    php {{ www_base }}/backend/bin/console azuracast:setup
  when: not update_mode|bool

- name: Run AzuraCast Setup (Update Mode)
  become: true
  become_user: azuracast
  shell: php {{ www_base }}/backend/bin/console azuracast:setup --update
  when: update_mode|bool

- name: Install PHP Jobs  Supervisord conf
  template:
    src: supervisor.conf.j2
    dest: /etc/supervisord.d/php-jobs.conf
    force: true
    mode: 0644