---
- name: Reset nodejs module
  shell: dnf module reset nodejs -y

- name: Enable nodejs 20 module
  shell: dnf module enable nodejs:20 -y

- name: "Install nodejs"
  dnf:
    name: nodejs
    state: present

- name: Set permissions for folders
  file: path="{{ item }}" state=directory owner=azuracast group=www-data mode=0744
  with_items:
    - "{{ www_base }}/frontend/node_modules"
    - "{{ www_base }}/web/static"
    - "{{ www_base }}/web/static/dist"
    - "{{ www_base }}/web/static/vite_dist"

- name: Pull Node Dependencies
  become: true
  become_user: azuracast
  command: >-
    npm ci
  args:
    chdir: "{{ www_base }}"


- name: Build AzuraCast Frontend Scripts (Production)
  become: true
  become_user: azuracast
  command: >-
    node ./node_modules/vite/bin/vite.js build
  args:
    chdir: "{{ www_base }}"
  when: 
    - app_env == "production"
  
- name: Remove file (delete file)
  ansible.builtin.file:
    path: /etc/supervisord.d/vite.conf
    state: absent
  when: 
    - app_env == "production"
  ignore_errors: true

- name: Install Vite Supervisor (Development)
  template:
    src: vite_supervisor.conf.j2
    dest: /etc/supervisord.d/vite.conf
    force: true
    mode: 0644
  when: 
    - app_env == "development"

- name: Set permissions of generated frontend content
  command: >-
    {{ azuracast_build_perm_command }}
  loop:
    - "chown -R azuracast:www-data {{ www_base }}"
    - "find {{ www_base }} -type d -exec chmod 755 {} \\;"
    - "find {{ www_base }} -type f -exec chmod 644 {} \\;"
  loop_control:
    loop_var: azuracast_build_perm_command
  # Note: Don't add warn: false here, it's incompatible with the earlier Ansibles used in 16.04/18.04.