---
- name: Install mutagen python package
  ansible.builtin.pip:
    name: mutagen

- name: Download autocue
  get_url:
    url: https://github.com/Moonbase59/autocue/archive/refs/tags/v4.0.2.tar.gz
    dest: "/tmp/autocue.tar.gz"
    force: true

- name: Extract autocue
  unarchive:
    src: "/tmp/autocue.tar.gz"
    dest: "/tmp/"
    remote_src: true

- name: Copy autocue bin
  ansible.builtin.copy:
    src: /tmp/autocue-4.0.2/cue_file
    dest: /usr/local/bin/cue_file
    owner: azuracast
    group: azuracast
    mode: 'a+x'

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{app_base}}/autocue"
    state: directory
    owner: azuracast
    group: azuracast

- name: Copy autocue liq file
  ansible.builtin.copy:
    src: /tmp/autocue-4.0.2/autocue.cue_file.liq
    dest: "{{app_base}}/autocue/autocue.liq"
    owner: azuracast
    group: azuracast
