---
- name: Install IceCast-KH-AC Dependencies
  dnf:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - libxml2
      - libxslt
      - libxml2-devel
      - libxslt-devel
      - libvorbis
      - libogg
      - libvorbis-devel
      - libogg-devel
      - openssl-devel
      - libcurl-devel
      - pkg-config

- name: Download IceCast-KH-AC Source
  get_url:
    url: https://github.com/karlheyes/icecast-kh/archive/refs/tags/icecast-2.4.0-kh22.tar.gz
    dest: "{{ app_base }}/servers/icecast2/icecast2.tar.gz"
    force: true

- name: Extract IceCast-KH-AC Source
  unarchive:
    src: "{{ app_base }}/servers/icecast2/icecast2.tar.gz"
    dest: "{{ app_base }}/servers/icecast2"
    remote_src: true
    mode: "u=rwx,g=rx,o=rx"
    owner: "azuracast"
    group: "www-data"
    extra_opts: "--strip-components=1"

- name: Build IceCast-KH-AC
  shell: "cd {{ app_base }}/servers/icecast2 && ./configure && make && make install"
  args:
    chdir: "{{ app_base }}/servers/icecast2"

- name: Download Custom Icecast Web Files
  ansible.builtin.git:
    repo: 'https://github.com/Yahav/icecast-kh-custom-files.git'
    dest: /tmp/icecast-kh-custom-files
    version: main

- name: Move Custom Icecast Web Files
  ansible.builtin.copy:
    src: /tmp/icecast-kh-custom-files/web
    dest: /usr/local/share/icecast/
    remote_src: true
  become: true
  become_user: root

  