---
- name: Clear OPAM directory
  file:
    path: "{{ app_base }}/.opam"
    state: absent


- name: Install Liquidsoap Dependencies
  dnf:
    name: "{{ packages }}"
    enablerepo: raven-extras
  vars:
    packages:
      - libpng-devel
      - bubblewrap
      - freetype-devel
      - gd
      - gd-devel
      - libjpeg-devel
      - portaudio-devel
      - SDL2-devel
      - SDL2_image-devel
      - SDL2_ttf-devel
      # - libswresample-free-devel
      # - libswscale-free-devel
      - taglib-devel
      - libtiff-devel
      - libX11-devel
      - libXpm-devel
      - file-libs
      - file-devel
      - libao
      - libao-devel
      - faad2-libs
      - faad2-devel
      - fdk-aac-devel
      - ffmpeg-devel
      - jack-audio-connection-kit
      - jack-audio-connection-kit-devel
      - flac-libs
      - flac-devel
      - opus-devel
      - speex-devel
      - libtheora-devel
      - libmad-devel
      - pulseaudio-libs-devel
      - libsamplerate-devel
      - soundtouch-devel
      - srt-devel




- name: Install ocaml
  become: false
  shell: "{{item}}"
  with_items:
    - opam init -a
    - opam install -y -q magic dune pulseaudio ao ogg srt ssl taglib tls-liquidsoap opus taglib lilv mad lame faad speex imagelib theora vorbis gd flac fdkaac cry samplerate soundtouch lo shine ffmpeg ffmpeg-av  ffmpeg-avcodec ffmpeg-avdevice ffmpeg-avfilter ffmpeg-avutil bjack portaudio liquidsoap


- name: Install Optional Audio Plugins
  apt:
    name: "{{ packages }}"
    install_recommends: false
  vars:
    packages:
      - frei0r-plugins-dev
      - ladspa-sdk
      - multimedia-audio-plugins
      - swh-plugins
      - tap-plugins
      - lsp-plugins-ladspa

- name: Get the DPKG Architecture
  shell: dpkg --print-architecture
  register: dpkg_arch
  ignore_errors: true

- name: Remove Existing Liquidsoap Packages
  apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
      - liquidsoap
      - liquidsoap-snapshot
  ignore_errors: true

- name: Install Liquidsoap
  apt:
    deb: "https://github.com/savonet/liquidsoap/releases/download/v2.1.3/liquidsoap_2.1.3-ubuntu-{{ ansible_distribution_release }}-1_{{ dpkg_arch.stdout_lines[0] | default('amd64') }}.deb"

- name: Link Liquidsoap binary
  file:
    src: "/usr/bin/liquidsoap"
    dest: /usr/local/bin/liquidsoap
    state: link
    force: true
