---
- name: Remove Old PHP Libraries
  dnf:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
      - "php"
      - "php-cli"
      - "php-fpm"
      - "php5-*"
      - "php7-*"
      - "php71-*"
      - "php72-*"
      - "php74-*"
      - "php80-*"
      - "php81-*"
      - "php82-*"
      - "php83-*"
  ignore_errors: true


- name: Set PHP Version
  set_fact:
    php_version: 8.3

- name: Reset php {{ php_version }} Remi module
  shell: dnf module reset php -y

- name: Enable php {{ php_version }} Remi module
  shell: dnf module enable php:remi-{{ php_version }} -y

- name: "Install PHP {{ php_version }}"
  dnf:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - "php-fpm"
      - "php-cli"
      - "php-common"
      - "php-gd"
      - "php-curl"
      - "php-pdo"
      - "php-ffi"
      - "php-xml"         # IceCast XML config
      - "php-zip"         # Composer installs
      - "php-mysqlnd"     # MySQL Native Driver (Doctrine)
      - "php-mbstring"    # Codeception Tests
      - "php-intl"        # Localization
      - "php-redis"       # Cache
      - "php-bcmath"      # BigInteger
      - "php-gmp"         # BigInteger and PHP-IP
      - "php-maxminddb"   # Maxmind (GeoIP) DB native ext
      - "php-opcache"   # Maxmind (GeoIP) DB native ext


- name: Configure PHP FPM Pool
  template:
    src: fpmpool.j2
    dest: "/etc/php-fpm.conf"
    force: true
    mode: 0644

- name: Configure php.ini
  ini_file:
    dest: "/etc/php.ini"
    section: PHP
    option: "{{ php_init_option.option }}"
    value: "{{ php_init_option.value }}"
    mode: 0644
  loop:
    - option: "post_max_size"
      value: "50M"
    - option: "short_open_tag"
      value: "On"
    - option: "upload_max_filesize"
      value: "50M"
    - option: "memory_limit"
      value: "256M"
    - option: "max_execution_time"
      value: "30"
  loop_control:
    loop_var: php_init_option

- name: Copy opcache configs
  template:
    src: opcache.ini.j2
    dest: /etc/php.d/90-opcache.ini
    force: true
    mode: 0644

- name: Copy opcache configs
  template:
    src: opcache.ini.j2
    dest: /etc/php-zts.d/90-opcache.ini
    force: true
    mode: 0644

- name: Configure ffi
  ini_file:
    dest: "/etc/php.ini"
    section: ffi
    option: "ffi.enable"
    value: "true"
    mode: 0644

- name: Install PHP-FPM Supervisord conf
  template:
    src: supervisor.conf.j2
    dest: /etc/supervisord.d/php-fpm.conf
    force: true
    mode: 0644

- name: Disable PHP-FPM service
  systemd_service:
    name: "php-fpm"
    enabled: false
    state: stopped
  ignore_errors: true
  when: is_systemd == "True"
