---
- name: Set Permissions on Base App Folder
  file:
    path: "{{ app_base }}"
    state: directory
    owner: azuracast
    group: www-data
    mode: 0775

- name: Copy existing INI file if it exists
  copy:
    src: "{{ www_base }}/azuracast.env"
    dest: "{{ app_base }}/azuracast.env"
  ignore_errors: true

- name: Clear temp directory
  file:
    path: "{{ tmp_base }}"
    state: absent

- name: Clear www directory
  file:
    path: "{{ www_base }}"
    state: absent
  when: 
    - app_env == "production"

- name: Create System Folders
  file:
    path: "{{ azuracast_config_sys_directory }}"
    state: directory
    owner: azuracast
    group: www-data
    mode: 0775
  loop:
    - "{{ www_base }}"
    - "{{ tmp_base }}"
    - "{{ app_base }}/stations"
    - "{{ app_base }}/centrifugo"
    - "{{ app_base }}/docs"
    - "{{ app_base }}/backups"
    - "{{ app_base }}/dbip"
    - "{{ app_base }}/geoip"
    - "{{ app_base }}/sftpgo"
    - "{{ app_base }}/storage"
    - "{{ app_base }}/storage/uploads"
    - "{{ app_base }}/storage/shoutcast2"
    - "{{ app_base }}/storage/stereo_tool"
    - "{{ app_base }}/storage/geoip"
    - "{{ app_base }}/storage/sftpgo"
    - "{{ app_base }}/storage/acme"
    - "{{ app_base }}/storage/acme/challenges" 
  loop_control:
    loop_var: azuracast_config_sys_directory

- name: Change tmp permissions
  ansible.builtin.file:
    path: "{{ tmp_base }}"
    owner: azuracast
    group: www-data
    mode: '0777'

- name: Write environment configuration file
  template:
    src: azuracast.env.j2
    dest: "{{ app_base }}/azuracast.env"
    owner: azuracast
    group: www-data
    mode: 0644
    force: false

- name: Set up environment file
  ini_file:
    dest: "{{ app_base }}/azuracast.env"
    option: "APPLICATION_ENV"
    value: "{{ app_env }}"
    mode: 0644
