---

- hosts: all
  become: true

  collections:
    - community.general
    
  vars:
    ansible_base: "{{ playbook_dir | dirname }}"
    app_base: "/usr/local/azuracast"
    www_base: "{{ app_base }}/www"
    tmp_base: "{{ app_base }}/www_tmp"
    app_env: "production"
    update_mode: false
    dev_azuracast_user_password: "azuracast"
    dev_mysql_user_password: "azuracast"

  environment:

  roles:
    - role: init
      tags: init
    - role: azuracast-user
      tags: azuracast-user
    - role: azuracast-config
      tags: azuracast-config
    - role: azuracast-radio
      tags: azuracast-radio
    - role: supervisord
      tags: supervisord
    - role: nginx
      tags: nginx
    - role: php
      tags: php
    - role: redis
      tags: redis
    - role: centrifugo
      tags: centrifugo
    - role: sftpgo
      tags: sftpgo
    - role: mariadb
      tags: mariadb
    - role: ufw
      tags: ufw
    - role: dbip
      tags: dbip
    - role: composer
      tags: composer
    - role: services
      tags: services
    - role: azuracast-db-install
      tags: azuracast-db-install
    - role: azuracast-build
      tags: azuracast-build
    - role: azuracast-setup
      tags: azuracast-setup
    - role: azuracast-cron
      tags: azuracast-cron
