---
- hosts: all
  become: true

  collections:
  - community.general

  vars:
    ansible_base: "{{ playbook_dir | dirname }}"
    app_base: "/var/azuracast"
    www_base: "{{ app_base }}/www"
    tmp_base: "{{ app_base }}/www_tmp"
    app_env: "production"
    update_mode: true
    update_revision: 1
    azuracast_repo: "AzuraCast/AzuraCast"
    azuracast_ref: "heads/" 
    azuracast_ver: "main"
    azuracast_dev_repo: "AzuraCast/AzuraCast" # Your repo name
    azuracast_dev_ver: "dev" # Our repo development branch

  roles:
    - role: "init"

    - role: "azuracast-config"

    - role: "azuracast-radio"
      when: update_revision|int < 1

    - role: "supervisord"

    - role: "nginx"
      when: update_revision|int < 1

    - role: "php"
      when: update_revision|int < 1

    - role: "redis"
      when: update_revision|int < 1

    - role: centrifugo
      when: update_revision|int < 1

    - role: "sftpgo"
      when: update_revision|int < 1

    - role: "mariadb"
      when: update_revision|int < 1

    - role: "ufw"
      when: update_revision|int < 1

    - role: "dbip"
      when: update_revision|int < 1

    - role: "composer"

    - role: "azuracast-cron"
      when: update_revision|int < 1

    - role: "services"

    - role: "azuracast-build"

    - role: "azuracast-setup"

    - role: services # We need this again to start newly added services
