---
- name: Install or Update Composer
  shell: >-
    curl -fsSL https://getcomposer.org/installer
    | php -- --install-dir=/usr/bin --filename=composer


- name: Download Azuracast Release
  get_url:
    url: "https://github.com/{{azuracast_repo}}/archive/refs/{{azuracast_ref}}/{{azuracast_ver}}.tar.gz"
    dest: "/tmp/azuracast-{{azuracast_ver}}.tar.gz"
    force: true

- name: Extract Azuracast
  unarchive:
    src: "/tmp/azuracast-{{azuracast_ver}}.tar.gz"
    dest: "/tmp"
    remote_src: true
    owner: azuracast
    group: www-data

- name: Move Azuracast files to www
  shell: "rsync -av /tmp/AzuraCast-{{azuracast_ver}}/ {{ www_base }}/ && rm -rf /tmp/AzuraCast-{{azuracast_ver}}"

- name: Install Deps (Development)
  become: true
  become_user: azuracast
  command: >-
    composer install
  args:
    chdir: "{{ www_base }}"
  when: 
    - app_env == "development"

- name: Install Deps (Production)
  become: true
  become_user: azuracast
  command: >-
    composer install --no-dev
  args:
    chdir: "{{ www_base }}"
  when: 
    - app_env == "production"
