---
- name: Install or Update Composer
  shell: >-
    curl -fsSL https://getcomposer.org/installer
    | php -- --install-dir=/usr/bin --filename=composer


- name: Download Azuracast Release
  get_url:
    url: "https://github.com/{{azuracast_repo}}/archive/refs/{{azuracast_ref}}/{{azuracast_ver}}.tar.gz"
    dest: "/tmp/azuracast-{{azuracast_ver}}.tar.gz"
    force: true
  when: 
    - app_env == "production"

# - name: Mount an NFS volume
#   ansible.posix.mount:
#     src: "{{ azuracast_dev_nfs }}"
#     path: "{{ www_base }}/"
#     opts: nfsvers=3,nolock,soft,rw
#     state: mounted
#     fstype: nfs
#   when: 
#     - app_env == "development"

# - name: Copying ssh key for github auth
#   become: true
#   become_user: azuracast
#   ansible.builtin.copy:
#     src: "{{ansible_base}}/ansible/.ssh/id_ed25519"
#     dest: ~/.ssh/id_ed25519

# - name: Starting SSH Agent and adding key
#   become: true
#   become_user: azuracast
#   ansible.builtin.shell: eval "$(ssh-agent -s)" && chmod 400 ~/.ssh/id_ed25519 && ssh-add ~/.ssh/id_ed25519


- name: Checking out the dev branch
  become: true
  become_user: azuracast
  ansible.builtin.git:
    repo: git@github.com:{{azuracast_repo}}.git
    dest: "{{ www_base }}/"
    version: dev
    accept_hostkey: yes


- name: Extract Azuracast
  unarchive:
    src: "/tmp/azuracast-{{azuracast_ver}}.tar.gz"
    dest: "/tmp"
    remote_src: true
    owner: azuracast
    group: www-data
  when: 
    - app_env == "production"

- name: Move Azuracast files to www
  shell: "rsync -av /tmp/AzuraCast-{{azuracast_ver}}/ {{ www_base }}/ && rm -rf /tmp/AzuraCast-{{azuracast_ver}}"
  when: 
    - app_env == "production"

- name: Install Deps (Development)
  become: true
  become_user: azuracast
  command: >-
    composer install
  args:
    chdir: "{{ www_base }}"
  when: 
    - app_env == "development"

- name: Install Deps (Production)
  become: true
  become_user: azuracast
  command: >-
    composer install --no-dev
  args:
    chdir: "{{ www_base }}"
  when: 
    - app_env == "production"
