---
- name: Install supervisord from repo
  dnf:
    name: supervisor

- name: Change supervisord configuration
  template:
    src: supervisord.conf.j2
    dest: /etc/supervisord.conf
    force: true
    mode: 0644

- name: Temporarily turn off supervisord
  systemd_service:
    name: "supervisord"
    enabled: true
    state: stopped
  ignore_errors: true
  when: is_systemd == True
