---
- name: Generate AzuraCast Password
  command: >-
    pwgen 8 -sn 1
  register: prod_azuracast_user_password

- name: Assign User Password
  set_fact:
    azura_user_password: "{{ prod_azuracast_user_password.stdout if app_env == 'production' else dev_azuracast_user_password }}"

- name: Create Groups
  group:
    name: "{{ azuracast_user_sys_group }}"
    state: present
  loop:
    - www-data
    - admin
  loop_control:
    loop_var: azuracast_user_sys_group

- name: Create AzuraCast User
  user:
    name: azuracast
    home: "{{ app_base }}"
    comment: "AzuraCast"
    shell: /bin/bash
    groups: 'wheel,admin,www-data'
    password: "{{ prod_azuracast_user_password.stdout|password_hash('sha512') if app_env == 'production' else dev_azuracast_user_password|password_hash('sha512') }}"
  notify: send user notification

- name: sudo without password for wheel group
  copy:
    content: 'azuracast ALL=(ALL:ALL) NOPASSWD:ALL'
    dest: /etc/sudoers.d/azuracast_nopasswd
    mode: 0440

- name: Modify www-data User
  user:
    name: www-data
    groups: "azuracast"
    append: true
